### ISSUE TITLE
SecurityException Package android does not belong to 10309

### ISSUE THREAD

**Issue by shumidub** [flurry/flurry-android-sdk#17]
I am started to get crashes on android 11.

java.lang.SecurityException: Package android does not belong to 10379
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2385)
       at android.os.Parcel.createException(Parcel.java:2369)
       at android.os.Parcel.readException(Parcel.java:2352)
       at android.os.Parcel.readException(Parcel.java:2294)
       at android.net.IConnectivityManager$Stub$Proxy.getNetworkCapabilities(IConnectivityManager.java:3347)
       at android.net.ConnectivityManager.getNetworkCapabilities(ConnectivityManager.java:1545)
       at com.flurry.sdk.av.getNetworkTypeM(av.java:508)
       at com.flurry.sdk.av.b(av.java:181)
       at com.flurry.sdk.av.c(av.java:408)
       at com.flurry.sdk.av.<init>(av.java:153)
       at com.flurry.sdk.n.<init>(n.java:1071)
       at com.flurry.sdk.n.a(n.java:48)
       at com.flurry.sdk.bn.<init>(bn.java:42)
       at com.flurry.sdk.bs.<init>(bs.java:24)
       at com.flurry.sdk.ey.<init>(ey.java:37)
       at com.flurry.sdk.fb.<init>(fb.java:1014)
       at com.flurry.sdk.fb.a(fb.java:30)
       at com.flurry.android.FlurryAgent$Builder.build(FlurryAgent.java:2120)

![изображение](https://user-images.githubusercontent.com/28213564/100548159-ee946180-327b-11eb-83c0-e5988fa3b9db.png)
![изображение](https://user-images.githubusercontent.com/28213564/100548166-f94ef680-327b-11eb-98e9-af0a583b4f5a.png)
![изображение](https://user-images.githubusercontent.com/28213564/100548180-14216b00-327c-11eb-9e5d-e09231545cd1.png)

Flurry version is 12.6.0@aar

**Comment by shumidub** [comment]
The same crash on flurry 12.9.0@aar version


Fatal Exception: java.lang.RuntimeException: Unable to create application App: java.lang.SecurityException: Package android does not belong to 10293
       at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7442)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7378)
       at android.app.ActivityThread.access$1500(ActivityThread.java:302)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2119)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8429)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)


Caused by java.lang.SecurityException: Package android does not belong to 10293
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2385)
       at android.os.Parcel.createException(Parcel.java:2369)
       at android.os.Parcel.readException(Parcel.java:2352)
       at android.os.Parcel.readException(Parcel.java:2294)
       at android.net.IConnectivityManager$Stub$Proxy.getNetworkCapabilities(IConnectivityManager.java:3347)
       at android.net.ConnectivityManager.getNetworkCapabilities(ConnectivityManager.java:1549)
       at com.flurry.sdk.av.getNetworkTypeM(av.java:518)
       at com.flurry.sdk.av.b(av.java:191)
       at com.flurry.sdk.av.c(av.java:418)
       at com.flurry.sdk.av.<init>(av.java:163)
       at com.flurry.sdk.n.<init>(n.java:1071)
       at com.flurry.sdk.n.a(n.java:48)
       at com.flurry.sdk.bn.<init>(bn.java:43)
       at com.flurry.sdk.bs.<init>(bs.java:24)
       at com.flurry.sdk.ey.<init>(ey.java:38)
       at com.flurry.sdk.fb.<init>(fb.java:1014)
       at com.flurry.sdk.fb.a(fb.java:31)
       at com.flurry.android.FlurryAgent$Builder.build(FlurryAgent.java:2120)
       at com.tradingview.tradingviewapp.core.analytics.FlurryAnalyticsKt.flurryAnalytics(FlurryAnalyticsKt.java:89)
       at com.tradingview.tradingviewapp.App.setupAnalytics(App.java:142)
       at com.tradingview.tradingviewapp.App.onCreate(App.java:91)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
       at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7437)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7378)
       at android.app.ActivityThread.access$1500(ActivityThread.java:302)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2119)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8429)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by shumidub** [comment]
A lot of crashes in the background

**Comment by shumidub** [comment]
Please fix it, because smartphones with android 11 will more and more

**Comment by shumidub** [comment]
Crashes more and more

**Comment by shumidub** [comment]
![image](https://user-images.githubusercontent.com/28213564/106996815-bab14d00-6792-11eb-8cc5-140f9245c9b9.png)

**Comment by poting-oath** [comment]
Fix has been released in Flurry Android SDK 12.11.0.

**Comment by hanli-lee** [comment]
> Fix has been released in Flurry Android SDK 12.11.0.

hello， how did you fix this issue ?  do you have a commit ? we also met this issue.

**Comment by JiaheMozil** [comment]
hello， how did you fix this issue ? do you have a commit ? we also met this issue.

**Comment by poting-oath** [comment]
@hanli-lee @JiaheMozil Flurry SDK is not Open Source.

**Comment by barnhill** [comment]
Sure hope you dont consume open source software in Flurry.

**Comment by dmitrikudrenko** [comment]
> @hanli-lee @JiaheMozil Flurry SDK is not Open Source.

ну ты и крыса

**Comment by maxdroz** [comment]
For everyone, looking how to fix this same issue
They just surrounded `ConnectivityManager.getNetworkCapabilities` call in `try catch(e: Throwable)` block
