### ISSUE TITLE
Flurry Crash Fatal Exception: java.lang.OutOfMemoryError pthread_create (1040KB stack) 

### ISSUE THREAD

**Issue by sachin4203** [flurry/flurry-android-sdk#34]
Hello,

We recently updated to the new version of Flurry SDK version `14.0.0`

After updating we have started to receive Out of Memory Crashes. I'm attaching the stacktrace and Crashlytics reports below. We think it might be due to a bug on Flurry SDK. 

`implementation "com.flurry.android:analytics:14.0.0"`

```
Fatal Exception: java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:883)
       at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:975)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1391)
       at com.flurry.sdk.e.onActive(SourceFile:76)
       at com.flurry.sdk.i.a(SourceFile:203)
       at com.flurry.sdk.i.runAsync(SourceFile:113)
       at com.flurry.sdk.g.runAsync(SourceFile:24)
       at com.flurry.sdk.i.onActive(SourceFile:173)
       at com.flurry.sdk.i.a(SourceFile:217)
       at com.flurry.sdk.i.runAsync(SourceFile:113)
       at com.flurry.sdk.f.runAsync(SourceFile:238)
       at com.flurry.sdk.m.notifyObservers(SourceFile:75)
       at com.flurry.sdk.ap.a(SourceFile:164)
       at com.flurry.sdk.ap.onActivityPaused(SourceFile:62)
       at android.app.Application.dispatchActivityPaused(Application.java:466)
       at android.app.Activity.dispatchActivityPaused(Activity.java:1301)
       at android.app.Activity.onPause(Activity.java:2221)
       at androidx.fragment.app.FragmentActivity.onPause(FragmentActivity.java:388)
       at android.app.Activity.performPause(Activity.java:7978)
       at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1507)
       at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4521)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4482)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4434)
       at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2041)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7386)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

```

<img width="1136" alt="Screenshot 2023-01-25 at 10 18 05" src="https://user-images.githubusercontent.com/9072850/214525236-69d3e401-8a42-4b2b-a411-90485e820c34.png">

<img width="391" alt="Screenshot 2023-01-25 at 10 20 49" src="https://user-images.githubusercontent.com/9072850/214525607-82d274f9-1485-4dc7-b7f4-ef774bcefd71.png">

<img width="831" alt="Screenshot 2023-01-25 at 10 21 10" src="https://user-images.githubusercontent.com/9072850/214525918-1d996aef-b85f-474d-a373-0848f2f2269a.png">

**Comment by poting-oath** [comment]
@sachin4203 Please try the latest Flurry SDK release 14.2.0. Flurry will not create new thread when the device has low memory. Thanks!
